### ISSUE TITLE
Question: Are you planning to add support to compile a canister from C#?

### ISSUE THREAD

**Issue by bancroftway** [edjCase/ICP.NET#20]
I am currently participating in Motoko bootcamp, and it is quite clear to me that it has quite a way to go, to achieve maturity. I am wondering if it might be possible to compile wasm canisters from C# instead?

**Comment by Gekctek** [comment]
@bancroftway 
Short Answer:
No

Long Answer: 
Its complicated. As far as THIS library is concerned, there is no plan for that. This code is purely for the bridging between the outside world into the internet computer, like a REST api client. It could be integrated into some C# canister, assuming something like that exists, but at the current time there is not.
The problem is a couple things:
- C# doesn't have much support for WASM compilation in general. Ive seen projects like https://github.com/SteveSandersonMS/dotnet-wasi-sdk and Blazor use wasm but its not officially supported to do standalone wasm from C# code
- WASM isnt enough for making a canister, it has to support the IC CDK or canister development kit, which essentially means C# needs to implement the IC canister functionality, which doesn't exist right now
- The canisters can't support large WASM files at the moment, so doing a C# wasm MIGHT be too large (unknown) because the entire .NET runtime has to be packaged in the wasm file as well

If you are looking for maturity the option right now is Rust. Motoko is getting there but needs more libraries and core language features. 
If you want something else the only options I know of are Azle (Typescript https://github.com/demergent-labs/azle) and Kybra (Python https://github.com/demergent-labs/kybra) but both of those are in early development. So they will have the language and libraries, but there may be complexity and issues with some features
