### ISSUE TITLE
[BUG] multiple tuple conflict

### ISSUE THREAD

**Issue by kentsday** [edjCase/ICP.NET#55]
version 2.10

candid

```
service : (opt InitArgs) -> {
    get_named_principal : () -> (
    vec record { PrincipalNames; vec principal },
    ) query;
    get_wasm_info : () -> (vec record { text; text }) query;
}
```

but

```cs
public class Arg0ItemRecord
{
	[CandidTag(0U)]
	public Models.PrincipalNames F0 { get; set; }

	[CandidTag(1U)]
	public List<Principal> F1 { get; set; }

	public Arg0ItemRecord(Models.PrincipalNames f0, List<Principal> f1)
	{
		this.F0 = f0;
		this.F1 = f1;
	}

	public Arg0ItemRecord()
	{
	}
}

public class Arg0ItemRecord
{
	[CandidTag(0U)]
	public string F0 { get; set; }

	[CandidTag(1U)]
	public string F1 { get; set; }

	public Arg0ItemRecord(string f0, string f1)
	{
		this.F0 = f0;
		this.F1 = f1;
	}

	public Arg0ItemRecord()
	{
	}
}
```

then 

```
  xxxApiClient.cs(136, 16): [CS0102] The type 'xxxApiClient' already contains a definition for 'Arg0ItemRecord'
```

**Comment by Gekctek** [comment]
@kentsday You are on 🔥 finding these issues. I appreciate it.
This one has been causing me some issues in general: What do you name anonymous objects with no parent object?

I think in this case Ill try to prefix them with the method name? Either that or ill have to just detect if there are collisions and just tweak one

Good chance you already know but most of this client generator generated code can be tweaked by you and should still work. That being said this will still be fixed because its a problem

If you dont mind me asking, what project are you working on? The only people that I have worked with are Unity developers, are you also doing a game?

**Comment by Gekctek** [comment]
@kentsday try version 2.1.1
